### ISSUE TITLE
Moving the Function (F1) key

### ISSUE THREAD

**Issue by babarrett** [VikOlliver/Microwriter#3]
Hi,
Looks like the numeric table starts out:
    `const char numericTable[] = " 120...`
And the function table starts out:
    `const int funcTable[] = {KEY_F1, 0, KEY_F2, KEY_F10...`

Seems like F1 is mapped to the same chord as "Space" when mapping it to "One" is probably what was intended.

So, new line would start:
    `const int funcTable[] = {0, KEY_F1, KEY_F2...`
Thanks

**Comment by VikOlliver** [comment]
FInaly sorted it in the repo :)

**Comment by babarrett** [comment]
Thanks. Looks fine now. Closing this issue.
